name: .NET Core Desktop build workflow

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/**"
      - "dotnet-demo-app/**"
  workflow_dispatch:

jobs:
  build:
    name: Build the application job
    runs-on: ubuntu-latest
    env:
      Solution_Name: DOTNET-DEMO-APP

    steps:
    # This step uses action
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # This step uses action
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    # This step runs a command
    - name: Check dotnet version
      run: dotnet --version

    # This step runs a command
    - name: List runtimes
      run: dotnet --list-runtimes
      
    # This step runs a command      
    - name: List SDKs
      run: dotnet --list-sdks
      
    # This step runs a command      
    - name: Build
      run: dotnet build
      working-directory: dotnet-demo-app

    # # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    # - name: Setup MSBuild.exe
    #   uses: microsoft/setup-msbuild@v2

    # # Execute all unit tests in the solution
    # - name: Execute unit tests
    #   run: dotnet test

    # # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
    #   env:
    #     Configuration: ${{ matrix.configuration }}

    # # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: MSIX Package
    #     path: ${{ env.Wap_Project_Directory }}\AppPackages
